Repository PDLPorters/pdl, pull requests merged in 2019-04, with the labels that each got.

#149 add a warning if the optional PGPLOT dependency is not available
  Graphics/PGPLOT/PGPLOT.pm
  Graphics/PGPLOT/Window/Window.pm
Labels: pr:wip

#51 Add propagation of badflag with .= (Ops::assgn) for sf.net bug 3543056.
  Basic/Ops/ops.pd
  t/ops.t
Labels: cat:type-system, pr:wip

#58 add vsearch example
  Basic/Primitive/primitive.pd
Labels: cat:doc, pr:wip
